apiVersion: v2
name: loki-distributed
description: Vendored reference chart folder for grafana/loki-distributed. Use custom-values.yaml for repository-specific overrides.
type: application
version: 0.80.5
appVersion: 2.9.13
home: https://grafana.com/oss/loki/
sources:
  - https://github.com/grafana/helm-charts
  - https://github.com/grafana/loki
annotations:
  vendoredFrom: grafana/loki-distributed
  repository: https://grafana.github.io/helm-charts
